sudo : required
language: generic
services:
  - docker
before_install:
  - docker build -t aminebelroulccie/docker-react  .
#script:
#  # for node and react
#  - docker run  -e CI=true aminebelroulccie/docker-react npm run test



deploy:
  provider: heroku
  api_key: "7cf7770a-e975-4db8-8489-7b8e17b09e28"
  app: "aminebelroulccie-docker"
  on:
    branch: master
  run: docker run -t aminebelroulccie/docker-react



#aws
#  provider: elasticbeanstalk
#  region: "europe"
#  app: "aminebelroulccie-docker"
#  env: "Aminebelroulccie-docker-env"
#  bucket_name: "s3 backet"
#  bucket_path: "aminebelroulccie-docker"
#  on:
#    branch: master
#  access_key_id: $API_ACCESS_KEY
#  secret_access_key:
#    secure: $API_SECURE_KEY




