sudo : required
services:
  - docker
before_install:
  - docker build -t aminebelroulccie/docker-react -f Dockerfile.dev .
script:
  - docker run aminebelroulccie/docker-react npm run test -- --coverage
