sudo : required
language: generic
services:
  - docker
before_install:
  - docker build -t aminebelroulccie/docker-react  .
script:
  # for node and react
  - docker run  -e CI=true aminebelroulccie/docker-react npm run test
deploy:
  provider: heroku
  api_key: "cbe7d290-5f19-4523-826b-67e0e8450179"
  app: "aminebelroulccie-docker"
  on:
    branch: master

  #aws
#  provider: elasticbeanstalk
#  region: "europe"
#  app: "aminebelroulccie-docker"
#  env: "Aminebelroulccie-docker-env"
#  bucket_name: "s3 backet"
#  bucket_path: "aminebelroulccie-docker"
#  on:
#    branch: master
#  access_key_id: $API_ACCESS_KEY
#  secret_access_key:
#    secure: $API_SECURE_KEY




